# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.synced_folder "../../logics", "/srv/logics"
  config.vm.hostname = 'koga'
  config.vm.network "private_network",ip:"192.168.8.8"
  config.vm.network "forwarded_port", guest:8080 , host:8080
  config.vm.provision :shell, :path => "koga_dev_setup.sh"
end
