# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.synced_folder "../../koga", "/srv/koga"
  config.vm.hostname = 'koga'
  config.vm.network "private_network",ip:"192.168.8.8"
  config.vm.network "forwarded_port", guest:880 , host:880, auto_correct: true 
  config.vm.provision :shell, :path => "koga_dev_setup.sh"
end
